version: '2.4'

services:
  Vyper:
    image: octoprint/octoprint
    restart: unless-stopped
    ports:
      - 5000:80
    devices:
      # Use ls /dev | grep 'ttyUSB\|ttyACM' to find printers
      - /dev/ttyUSB0:/dev/ttyUSB0
    #  - /dev/video0:/dev/video0
    volumes:
      - /home/essential-accident/octoprint/vyper:/octoprint
    # uncomment the lines below to ensure camera streaming is enabled when
    # you add a video device
    environment:
      - ENABLE_MJPG_STREAMER=false
    ####
    # uncomment if you wish to edit the configuration files of octoprint
    # refer to docs on configuration editing for more information
    ####

    #config-editor:
    #  image: linuxserver/code-server
    #  ports:
    #    - 8443:8443
    #  depends_on:
    #    - octoprint
    #  restart: unless-stopped
    #  environment:
    #    - PUID=0
    #    - GUID=0
    #    - TZ=America/Chicago
    #  volumes:
    #    - octoprint:/octoprint
