version: '3.6'

services:
  Vyper:
    container_name: vyper
    image: octoprint/octoprint
    hostname: vyper
    restart: unless-stopped
    ports:
      - 5000:5000
      - 8080:8080
    volumes:
      - /home/dietpi/docker/octoprint1:/vyper
    environment:
      - ENABLE_MJPG_STREAMER=true
      - MJPG_STREAMER_INPUT=-n -d /dev/video0:/dev/video0 -r 1280x720 -f 30
    devices:
      #Printer Port
      - /dev/ttyUSB0:/dev/ttyUSB0
    #Webcam port
    #  - /dev/video0:/dev/video0
